# Generated by Django 2.1.1 on 2018-11-22 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_vocab_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('side', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='crime_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('address', models.CharField(max_length=50)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('description', models.CharField(db_index=True, max_length=100)),
                ('location_desc', models.CharField(db_index=True, max_length=30)),
                ('arrest', models.CharField(max_length=30, null=True)),
                ('beat', models.IntegerField(null=True)),
                ('updated_time', models.DateTimeField(null=True)),
                ('violations', models.IntegerField(null=True)),
                ('intersection', models.CharField(max_length=50, null=True)),
                ('created_by_user', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='new_format',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('new_date', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=100)),
                ('new_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vocab_freq_central',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vocab_freq_east',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vocab_freq_north',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vocab_freq_south',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vocab_freq_west',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='new_format',
            unique_together={('new_date', 'description')},
        ),
    ]
